### PR TITLE
heheheh

### PR DESCRIPTION
**Pull request by blazecoding2009**

### CODE REVIEW

**Comment by blazecoding2009** [comment]
@aaronw-dev sigma

**Comment by aaronw-dev** [comment]
Did you really just @ me to say sigma 💀

**Comment by blazecoding2009** [comment]
yes

**Comment by blazecoding2009** [comment]
@EmperorNumerius for fucks sakes man give me write

**Comment by EmperorNumerius** [comment]
very sigma

**Comment by EmperorNumerius** [comment]
merging your own pr's is not oa good practice

**Comment by aaronw-dev** [comment]
> merging your own pr's is not oa good practice

True

**Comment by EmperorNumerius** [comment]
will give the main contributers full merge perms when we are done for submission reviewing

**Pull request merged**
